spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/jobboard
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  jwt:
    secret: ThisIsASecretKeyThatIsAtLeast32Chars
    expiration: 86400000  # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs