spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/jobboard
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourmail@gmail.com # gmail: cotsezer2000@gmail.com
    password: abcdefghijklmnop # google apps password: abcd efgh ijkl mnop
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8080

app:
  jwt:
    secret: ThisIsASecretKeyThatIsAtLeast32Chars
    expiration: 86400000  # 24 hours in milliseconds

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

file:
  upload-dir: /app/uploads/profile-pictures